[2022-12-08T03:38:23.110+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: streamify_dag.wait_in_seller_line_create_external_table manual__2022-12-08T03:38:13.154207+00:00 [queued]>
[2022-12-08T03:38:23.128+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: streamify_dag.wait_in_seller_line_create_external_table manual__2022-12-08T03:38:13.154207+00:00 [queued]>
[2022-12-08T03:38:23.128+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T03:38:23.129+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-08T03:38:23.129+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-08T03:38:23.161+0000] {taskinstance.py:1304} INFO - Executing <Task(BigQueryCreateExternalTableOperator): wait_in_seller_line_create_external_table> on 2022-12-08 03:38:13.154207+00:00
[2022-12-08T03:38:23.171+0000] {standard_task_runner.py:55} INFO - Started process 133 to run task
[2022-12-08T03:38:23.184+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'streamify_dag', 'wait_in_seller_line_create_external_table', 'manual__2022-12-08T03:38:13.154207+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/ticketsim.py', '--cfg-path', '/tmp/tmpznq6vp87']
[2022-12-08T03:38:23.190+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask wait_in_seller_line_create_external_table
[2022-12-08T03:38:23.310+0000] {task_command.py:389} INFO - Running <TaskInstance: streamify_dag.wait_in_seller_line_create_external_table manual__2022-12-08T03:38:13.154207+00:00 [running]> on host 1222418420bc
[2022-12-08T03:38:23.439+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=streamify_dag
AIRFLOW_CTX_TASK_ID=wait_in_seller_line_create_external_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T03:38:13.154207+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-08T03:38:13.154207+00:00
[2022-12-08T03:38:23.443+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-12-08T03:38:23.444+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-12-08T03:38:24.075+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1592, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 403, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/elite-bird-367213/datasets/ticketsim/tables?prettyPrint=false: Not found: Dataset elite-bird-367213:ticketsim
[2022-12-08T03:38:24.105+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=streamify_dag, task_id=wait_in_seller_line_create_external_table, execution_date=20221208T033813, start_date=20221208T033823, end_date=20221208T033824
[2022-12-08T03:38:24.135+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task wait_in_seller_line_create_external_table (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/elite-bird-367213/datasets/ticketsim/tables?prettyPrint=false: Not found: Dataset elite-bird-367213:ticketsim; 133)
[2022-12-08T03:38:24.166+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-08T03:38:24.195+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
